#######################################
#                                     #
# Lights                              #
#                                     #
#######################################
#
#
# Sonoff MQTT Light Devices
#
#
#

# Laundry Door Open Buzzer
#- platform: mqtt
#  name: "Laundry"
#  state_topic: "stat/laundry/RESULT"
#  command_topic: "cmnd/laundry/PWM3"



#
# Family Room Lights
#
- platform: mqtt
  name: "Foyer"
  state_topic: "stat/foyer/POWER"
  command_topic: "cmnd/foyer/power"
  qos: 0
  payload_on: "ON"
  payload_off: "OFF"
  retain: false

- platform: mqtt
  name: "Tall"
  state_topic: "stat/tall/POWER"
  command_topic: "cmnd/tall/power"
  qos: 0
  payload_on: "ON"
  payload_off: "OFF"
  retain: false

- platform: mqtt
  name: "Fireplace"
  state_topic: "stat/fireplace/POWER"
  command_topic: "cmnd/fireplace/power"
  qos: 0
  payload_on: "ON"
  payload_off: "OFF"
  retain: false

#
# Kitchen Lights
#

- platform: mqtt
  name: "Table"
  state_topic: "stat/table/POWER"
  command_topic: "cmnd/table/power"
  qos: 0
  payload_on: "ON"
  payload_off: "OFF"
  retain: false

- platform: mqtt
  name: "Island"
  state_topic: "stat/island/POWER"
  command_topic: "cmnd/island/power"
  qos: 0
  payload_on: "ON"
  payload_off: "OFF"
  retain: false

- platform: mqtt
  name: "Top"
  state_topic: "stat/top/POWER"
  command_topic: "cmnd/top/power"
  qos: 0
  payload_on: "ON"
  payload_off: "OFF"
  retain: false

#
# Boys' Rooms Lights
#

- platform: mqtt
  name: "Brandon"
  state_topic: "stat/brandon/POWER"
  command_topic: "cmnd/brandon/power"
  qos: 0
  payload_on: "ON"
  payload_off: "OFF"
  retain: false

#
# Dad's Office Lights
#

- platform: mqtt
  name: "Office"
  state_topic: "stat/office/POWER"
  command_topic: "cmnd/office/power"
  qos: 0
  payload_on: "ON"
  payload_off: "OFF"
  retain: false

